"""Pytest fixtures and configuration for AutoEvoExtractor tests."""

import json
import shutil
from pathlib import Path
from typing import Any, Dict, List

import pandas as pd
import pytest

# ============================================================================
# Test Data Paths
# ============================================================================

TEST_DATA_DIR = Path(__file__).parent / "data"


# ============================================================================
# Task Configuration Fixtures
# ============================================================================


@pytest.fixture(scope="module")
def nanozyme_task(tmp_nanozymes_task_yaml: Path, nanozyme_test_instruction_path: Path):
    """Get nanozyme task components.

    Uses module scope to avoid reloading task for every test.
    Uses temporary task YAML file generated by fixture to avoid dependency
    on external config files.

    Args:
        tmp_nanozymes_task_yaml: Path to temporary nanozymes.yaml file.
        nanozyme_test_instruction_path: Path to test instruction file.

    Returns:
        Dictionary with task components (config, experiment_model, output_model, row_converter).
        Note: signature is created lazily on first access as it requires instruction file.
    """
    from aee.domain.tasks import (
        create_all_models,
        create_row_converter,
        create_signature,
        load_task_from_yaml,
    )

    # Load task from temporary YAML (without instruction file initially)
    config = load_task_from_yaml(tmp_nanozymes_task_yaml)
    # Set instruction file from test data
    config.initial_instruction_file = str(nanozyme_test_instruction_path)

    # Generate models and converter directly
    experiment_model, output_model = create_all_models(config)
    row_converter = create_row_converter(config, experiment_model)

    # Create signature lazily (requires instruction file)
    _signature_cache = {}

    def get_signature():
        if "signature" not in _signature_cache:
            # For tests that need signature, use the test instruction file
            _signature_cache["signature"] = create_signature(
                config,
                experiment_model,
                output_model,
                instruction=config.get_instruction(),
            )
        return _signature_cache["signature"]

    return {
        "config": config,
        "experiment_model": experiment_model,
        "output_model": output_model,
        "row_converter": row_converter,
        "signature": get_signature(),  # Lazy access
    }


@pytest.fixture
def task_config_dict() -> Dict[str, Any]:
    """Sample task configuration dictionary.

    Returns:
        Dictionary with task configuration.
    """
    return {
        "name": "nanozymes",
        "compare_fields": [
            "formula",
            "activity",
            "length",
            "km_value",
            "vmax_value",
            "ph",
            "temperature",
        ],
        "float_tolerance": 0.10,
        # Note: initial_instruction_file not included - only needed for DSPy signatures
    }


# ============================================================================
# Ground Truth Data Fixtures
# ============================================================================


@pytest.fixture
def sample_gt_csv(tmp_path: Path) -> Path:
    """Create a sample ground truth CSV file.

    Args:
        tmp_path: Pytest temporary directory.

    Returns:
        Path to created CSV file.
    """
    csv_path = tmp_path / "gt.csv"
    csv_path.write_text(
        "filename,formula,activity,length,km_value,vmax_value,ph,temperature,surface\n"
        "paper1.pdf,Fe3O4,peroxidase,10,0.05,100,7.0,25.0,naked\n"
        "paper2.pdf,CuO,oxidase,20,0.08,150,7.5,30.0,PVP\n"
        "paper3.pdf,ZnO,catalase,15,0.06,120,6.8,28.0,PEG\n",
        encoding="utf-8",
    )
    return csv_path


@pytest.fixture
def sample_gt_dataframe(sample_gt_csv: Path) -> pd.DataFrame:
    """Load sample ground truth as DataFrame.

    Args:
        sample_gt_csv: Path to sample CSV.

    Returns:
        DataFrame with ground truth data.
    """
    return pd.read_csv(sample_gt_csv)


@pytest.fixture
def nanozyme_experiments(nanozyme_task) -> List:
    """Create a list of sample nanozyme experiments.

    Args:
        nanozyme_task: Task fixture providing experiment_model.

    Returns:
        List of experiment instances.
    """
    experiment_model = nanozyme_task["experiment_model"]
    return [
        experiment_model(
            formula="Fe3O4",
            activity="peroxidase",
            length=10.0,
            km_value=0.05,
            vmax_value=100.0,
            ph=7.0,
            temperature=25.0,
            surface="naked",
        ),
        experiment_model(
            formula="CuO",
            activity="oxidase",
            length=20.0,
            km_value=0.08,
            vmax_value=150.0,
            ph=7.5,
            temperature=30.0,
            surface="PVP",
        ),
    ]


@pytest.fixture
def nanozyme_output(nanozyme_task, nanozyme_experiments):
    """Create a sample extraction output.

    Args:
        nanozyme_task: Task fixture providing output_model.
        nanozyme_experiments: List of experiments.

    Returns:
        Extraction output instance.
    """
    output_model = nanozyme_task["output_model"]
    return output_model(experiments=nanozyme_experiments)


# ============================================================================
# Data Split Fixtures
# ============================================================================


@pytest.fixture
def sample_splits_json(tmp_path: Path) -> Path:
    """Create a sample splits JSON file.

    Args:
        tmp_path: Pytest temporary directory.

    Returns:
        Path to created JSON file.
    """
    splits_path = tmp_path / "splits.json"
    splits_data = {
        "train": ["paper1", "paper2"],
        "val": ["paper3"],
        "test": ["paper4", "paper5"],
    }
    splits_path.write_text(json.dumps(splits_data), encoding="utf-8")
    return splits_path


@pytest.fixture
def sample_splits_dict() -> Dict[str, List[str]]:
    """Sample splits dictionary.

    Returns:
        Dictionary with train/val/test splits.
    """
    return {
        "train": ["paper1", "paper2", "paper3"],
        "val": ["paper4"],
        "test": ["paper5"],
    }


# ============================================================================
# Agent Storage Fixtures
# ============================================================================


@pytest.fixture
def tmp_agents_dir(tmp_path: Path) -> Path:
    """Create a temporary agents directory.

    Args:
        tmp_path: Pytest temporary directory.

    Returns:
        Path to temporary directory.
    """
    agents_dir = tmp_path / "agents"
    agents_dir.mkdir(parents=True, exist_ok=True)
    return agents_dir


@pytest.fixture
def sample_agent_dict() -> Dict[str, Any]:
    """Create a sample agent dictionary.

    Returns:
        Dictionary representing a mock agent.
    """
    return {
        "lm": {
            "model": "test-model",
            "type": "mock",
        },
        "traces": [],
        "settings": {
            "num_trials": 5,
            "metric": "f1",
        },
    }


@pytest.fixture
def sample_agent_metadata() -> Dict[str, Any]:
    """Create sample agent metadata.

    Returns:
        Dictionary with agent metadata.
    """
    from datetime import datetime

    return {
        "task_name": "nanozymes",
        "created_at": datetime.now().isoformat(),
        "model_version": "test-model-v1",
        "metrics": {"f1": 0.85, "precision": 0.82, "recall": 0.88},
        "config_snapshot": {"num_trials": 5},
    }


# ============================================================================
# Document Fixtures
# ============================================================================


@pytest.fixture
def sample_parsed_document(tmp_path: Path) -> Path:
    """Create a sample parsed document Markdown file.

    Args:
        tmp_path: Pytest temporary directory.

    Returns:
        Path to created .md file.
    """
    parsed_dir = tmp_path / "parsed"
    parsed_dir.mkdir(parents=True, exist_ok=True)

    doc_path = parsed_dir / "paper1.md"
    doc_path.write_text("Sample parsed content from paper1.pdf.", encoding="utf-8")
    return doc_path


# ============================================================================
# Mock LLM Fixtures
# ============================================================================


@pytest.fixture
def mock_llm_response():
    """Create a mock LLM response.

    Returns:
        Dictionary with mock response data.
    """
    return {
        "extracted_data": {
            "experiments": [
                {
                    "formula": "Fe3O4",
                    "activity": "peroxidase",
                    "length": 10.0,
                    "km_value": 0.05,
                    "vmax_value": 100.0,
                    "ph": 7.0,
                    "temperature": 25.0,
                }
            ]
        }
    }


# ============================================================================
# Utility Fixtures
# ============================================================================


@pytest.fixture(autouse=True)
def reset_task_registry():
    """Automatically reset task registry after each test.

    This fixture ensures clean state between tests by clearing
    the global task registry before and after each test.
    """
    from aee.domain.tasks import get_global_registry

    registry = get_global_registry()
    # Clear before test
    registry.clear()
    yield
    # Clear after test
    registry.clear()


@pytest.fixture
def cleanup_temp_files():
    """Fixture to clean up temporary files after tests.

    Yields:
        Cleanup function.
    """
    temp_files = []

    def register_cleanup(path: Path):
        temp_files.append(path)
        return path

    yield register_cleanup

    # Cleanup
    for path in temp_files:
        if path.exists():
            if path.is_file():
                path.unlink()
            elif path.is_dir():
                shutil.rmtree(path)


# ============================================================================
# Comparison Data Fixtures
# ============================================================================


@pytest.fixture
def matched_pairs_data(nanozyme_task):
    """Create sample data for testing matcher alignment.

    Args:
        nanozyme_task: Task fixture providing experiment_model.

    Returns:
        Dictionary with test data for matching.
    """
    experiment_model = nanozyme_task["experiment_model"]
    return {
        "preds": [
            experiment_model(formula="Fe3O4", activity="peroxidase", length=10.0),
            experiment_model(formula="CuO", activity="oxidase", length=20.0),
        ],
        "gts": [
            experiment_model(formula="Fe3O4", activity="peroxidase", length=10.0),
            experiment_model(formula="ZnO", activity="catalase", length=15.0),
        ],
    }


@pytest.fixture
def experiment_model(nanozyme_task):
    """Get experiment model from nanozyme task.

    Args:
        nanozyme_task: Task fixture.

    Returns:
        Experiment model class.
    """
    return nanozyme_task["experiment_model"]


@pytest.fixture
def output_model(nanozyme_task):
    """Get output model from nanozyme task.

    Args:
        nanozyme_task: Task fixture.

    Returns:
        Output model class.
    """
    return nanozyme_task["output_model"]


@pytest.fixture
def row_converter(nanozyme_task):
    """Get row converter from nanozyme task.

    Args:
        nanozyme_task: Task fixture.

    Returns:
        Row converter function.
    """
    return nanozyme_task["row_converter"]


# ============================================================================
# Configuration File Fixtures
# ============================================================================

CONFIG_DATA_DIR = TEST_DATA_DIR / "configs"


@pytest.fixture
def minimal_config_path() -> Path:
    """Get path to minimal valid configuration file.

    Returns:
        Path to minimal_config.yaml
    """
    return CONFIG_DATA_DIR / "minimal_config.yaml"


@pytest.fixture
def llm_config_template_path() -> Path:
    """Get path to LLM configuration template file.

    Returns:
        Path to llm_config_template.yaml
    """
    return CONFIG_DATA_DIR / "llm_config_template.yaml"


@pytest.fixture
def minimal_config_with_custom_paths(tmp_path: Path, minimal_config_path: Path) -> Path:
    """Create a copy of minimal config with custom paths for isolated testing.

    Args:
        tmp_path: Pytest temporary directory.
        minimal_config_path: Path to minimal config template.

    Returns:
        Path to copied config file.
    """
    import shutil

    config_copy = tmp_path / "config.yaml"
    shutil.copy(minimal_config_path, config_copy)
    return config_copy


@pytest.fixture
def config_with_instruction_file(
    tmp_path: Path, llm_config_template_path: Path
) -> Path:
    """Create config with resolved instruction file path.

    Args:
        tmp_path: Pytest temporary directory.
        llm_config_template_path: Path to LLM config template.

    Returns:
        Path to config file with resolved instruction path.
    """

    # Create instruction file
    instruction_file = tmp_path / "config" / "initial_instructions" / "test.txt"
    instruction_file.parent.mkdir(parents=True, exist_ok=True)
    instruction_file.write_text("Test instruction")

    # Load template
    config_content = llm_config_template_path.read_text(encoding="utf-8")
    config_content = config_content.replace(
        "${INSTRUCTION_FILE_PATH}", str(instruction_file)
    )

    # Save resolved config
    config_file = tmp_path / "config.yaml"
    config_file.write_text(config_content, encoding="utf-8")

    return config_file


# ============================================================================
# Test Instruction File Fixtures
# ============================================================================

TEST_DATA_DIR = Path(__file__).parent / "data"
TEST_INSTRUCTION_FILE = TEST_DATA_DIR / "instructions" / "nanozymes_sota_test.txt"
TEST_CONFIG_FILE = TEST_DATA_DIR / "configs" / "nanozymes_test_config.yaml"


@pytest.fixture(scope="module")
def nanozyme_test_instruction_path() -> Path:
    """Get path to static test instruction file.

    Returns:
        Path to nanozymes_sota_test.txt in tests/data/instructions/.
    """
    return TEST_INSTRUCTION_FILE


@pytest.fixture(scope="module")
def nanozyme_test_config_path() -> Path:
    """Get path to static test configuration file.

    Returns:
        Path to nanozymes_test_config.yaml in tests/data/configs/.
    """
    return TEST_CONFIG_FILE


@pytest.fixture
def tmp_instruction_file(tmp_path: Path) -> Path:
    """Generate a temporary instruction file for unit tests.

    Args:
        tmp_path: Pytest temporary directory.

    Returns:
        Path to created instruction file.
    """
    instruction_file = (
        tmp_path / "config" / "initial_instructions" / "test_instruction.txt"
    )
    instruction_file.parent.mkdir(parents=True, exist_ok=True)
    instruction_file.write_text(
        "Extract structured data from scientific documents. "
        "Focus on key experimental parameters and results."
    )
    return instruction_file


@pytest.fixture
def tmp_config_with_instruction(tmp_path: Path, tmp_instruction_file: Path) -> Path:
    """Create a minimal config with resolved instruction file path.

    Args:
        tmp_path: Pytest temporary directory.
        tmp_instruction_file: Path to temporary instruction file.

    Returns:
        Path to created config file.
    """
    config_content = f"""
project:
  log_level: INFO
paths:
  pdf_dir: {tmp_path}/pdf
  parsed_dir: {tmp_path}/parsed
  ground_truth_dir: {tmp_path}/ground_truth
  splits_file: {tmp_path}/splits.json
  agents_dir: {tmp_path}/agents
  extractions_dir: {tmp_path}/extractions
task:
  name: nanozymes
  initial_instruction_file: {tmp_instruction_file}
llm:
  student:
    provider: "ollama"
    model: test-model
    timeout: 60
    max_retries: 1
    temperature: 0.0
    rate_limit_delay: 0.0
    top_p: 0.1
    enable_cache: false
    ollama:
      num_ctx: 1024
      num_predict: 256
      repeat_penalty: 1.0
      repeat_last_n: 64
      stream: false
    api:
      max_tokens: 256
  teacher:
    provider: "ollama"
    model: test-model
    timeout: 60
    max_retries: 1
    temperature: 0.5
    rate_limit_delay: 0.0
    top_p: 0.9
    enable_cache: false
    ollama:
      num_ctx: 1024
      num_predict: 256
      repeat_penalty: 1.0
      repeat_last_n: 64
      stream: false
    api:
      max_tokens: 256
parsing:
  parser: marker
  overwrite: false
  marker:
    device: cpu
optimization:
  num_trials: 1
  train_split: 5
  total_load: 10
  random_seed: 42
  num_candidates: 2
  max_bootstrapped_demos: 1
  max_labeled_demos: 1
  minibatch: false
  minibatch_size: 1
  view_data_batch_size: 1
  metric_threshold: 0.5
  init_temperature: 0.5
  verbose: false
  use_cache: false
  max_errors: 5
extraction:
  enable_cache: false
cache:
  disk_size_limit_bytes: 1000000
  memory_max_entries: 100
circuit_breaker:
  failure_threshold: 3
  reset_timeout: 30.0
  half_open_max_calls: 1
"""
    config_file = tmp_path / "config.yaml"
    config_file.write_text(config_content, encoding="utf-8")
    return config_file


# ============================================================================
# Task Configuration File Fixtures
# ============================================================================


@pytest.fixture(scope="session")
def tmp_nanozymes_task_yaml(tmp_path_factory) -> Path:
    """Generate a temporary nanozymes task YAML file for tests.

    This fixture creates a complete task configuration file in a temporary
    directory, ensuring tests don't depend on external config files.

    Args:
        tmp_path_factory: Pytest temporary directory factory for session scope.

    Returns:
        Path to created nanozymes.yaml file.
    """
    tmp_path = tmp_path_factory.mktemp("config")
    tasks_dir = tmp_path / "config" / "tasks"
    tasks_dir.mkdir(parents=True, exist_ok=True)

    yaml_content = """
name: nanozymes

fields:
  formula:
    type: str
    description: "Chemical formula (e.g., Fe3O4, Au, CuO)"
    required: true

  surface:
    type: str
    description: "Surface chemistry (naked, PEG, PVP, citrate)"
    required: false

  syngony:
    type: str
    description: "Crystal system: cubic, hexagonal, tetragonal, monoclinic"
    required: false

  length:
    type: float
    description: "Length or size/diameter in nm"
    required: false
    min_value: 0

  width:
    type: float
    description: "Width in nm (if applicable)"
    required: false
    min_value: 0

  depth:
    type: float
    description: "Depth in nm (if applicable)"
    required: false
    min_value: 0

  activity:
    type: str
    description: "Type of catalytic activity"
    required: true
    choices:
      - peroxidase
      - oxidase
      - catalase
      - laccase
      - superoxide_dismutase
      - glucose oxidase
      - other

  reaction_type:
    type: str
    description: "Format: Substrate + Co-substrate"
    required: false

  km_value:
    type: float
    description: "Michaelis constant Km (Mantissa)"
    required: false
    min_value: 0

  km_unit:
    type: str
    description: "Unit for Km (e.g., mM)"
    required: false

  vmax_value:
    type: float
    description: "Max reaction rate Vmax (Mantissa)"
    required: false
    min_value: 0

  vmax_unit:
    type: str
    description: "Unit for Vmax (e.g., M/s, mM/s)"
    required: false

  ph:
    type: float
    description: "pH level"
    required: false
    min_value: 0
    max_value: 14

  temperature:
    type: float
    description: "Temperature in degrees C"
    required: false

  c_min:
    type: float
    description: "Min concentration of variable substrate (mM)"
    required: false
    min_value: 0

  c_max:
    type: float
    description: "Max concentration of variable substrate (mM)"
    required: false
    min_value: 0

  c_const:
    type: float
    description: "Concentration of fixed co-substrate (mM)"
    required: false
    min_value: 0

  c_const_unit:
    type: str
    description: "Unit for c_const"
    required: false

  ccat_value:
    type: float
    description: "Concentration of the nanozyme/catalyst"
    required: false
    min_value: 0

  ccat_unit:
    type: str
    description: "Unit for catalyst conc (e.g., mcg/ml, mg/mL)"
    required: false

compare_fields:
  - formula
  - activity
  - syngony
  - surface
  - length
  - width
  - depth
  - reaction_type
  - km_value
  - km_unit
  - vmax_value
  - vmax_unit
  - ph
  - temperature
  - c_min
  - c_max
  - c_const
  - c_const_unit
  - ccat_value
  - ccat_unit

float_tolerance: 0.05

row_converter:
  formula:
    - formula
    - name
  surface:
    - surface
    - surface_chemistry
    - coating
  syngony:
    - syngony
    - crystal_system
  length:
    - length
    - size
    - diameter
  width:
    - width
  depth:
    - depth
  activity:
    - activity
    - catalytic_activity
  reaction_type:
    - reaction_type
    - reaction
  km_value:
    - km_value
    - km
    - km_val
  km_unit:
    - km_unit
  vmax_value:
    - vmax_value
    - vmax
    - vmax_val
  vmax_unit:
    - vmax_unit
  ph:
    - ph
    - pH
  temperature:
    - temperature
    - temp
  c_min:
    - c_min
    - cmin
  c_max:
    - c_max
    - cmax
  c_const:
    - c_const
    - ccons
    - c_cons
  c_const_unit:
    - c_const_unit
    - ccons_unit
  ccat_value:
    - ccat_value
    - ccat
  ccat_unit:
    - ccat_unit
"""

    yaml_path = tasks_dir / "nanozymes.yaml"
    yaml_path.write_text(yaml_content, encoding="utf-8")
    return yaml_path


@pytest.fixture(scope="session")
def tmp_example_system_yaml(tmp_path_factory) -> Path:
    """Generate a temporary example system YAML file for tests.

    This fixture creates a minimal system configuration file in a temporary
    directory, ensuring tests don't depend on external config files.

    Args:
        tmp_path_factory: Pytest temporary directory factory for session scope.

    Returns:
        Path to created example.yaml file.
    """
    tmp_path = tmp_path_factory.mktemp("systems")
    systems_dir = tmp_path / "config" / "systems"
    systems_dir.mkdir(parents=True, exist_ok=True)

    yaml_content = """
project:
  log_level: "INFO"

llm:
  student:
    provider: "ollama"
    model: "test-model"
    timeout: 60
    max_retries: 1
    temperature: 0.0
    rate_limit_delay: 0.0
    top_p: 0.1
    enable_cache: false
    ollama:
      num_ctx: 1024
      num_predict: 256
      repeat_penalty: 1.0
      repeat_last_n: 64
      stream: false
    api:
      max_tokens: 256

  teacher:
    provider: "ollama"
    model: "test-model"
    timeout: 60
    max_retries: 1
    temperature: 0.5
    rate_limit_delay: 0.0
    top_p: 0.9
    enable_cache: false
    ollama:
      num_ctx: 1024
      num_predict: 256
      repeat_penalty: 1.0
      repeat_last_n: 64
      stream: false
    api:
      max_tokens: 256

parsing:
  parser: "marker"
  overwrite: false
  marker:
    device: "cpu"

paths:
  pdf_dir: "data/pdf"
  parsed_dir: "data/parsed"
  ground_truth_dir: "data/ground_truth"
  splits_file: "data/splits.json"
  agents_dir: "data/agents"
  extractions_dir: "data/extractions"

optimization:
  total_load: 10
  train_split: 5
  num_candidates: 2
  num_trials: 1
  max_bootstrapped_demos: 1
  max_labeled_demos: 1
  minibatch: false
  minibatch_size: 1
  view_data_batch_size: 1
  metric_threshold: 0.5
  init_temperature: 0.5
  random_seed: 42
  use_cache: false
  verbose: false
  max_errors: 5

task:
  name: "nanozymes"
  initial_instruction_file: "${INSTRUCTION_FILE_PATH}"

extraction:
  enable_cache: false

cache:
  disk_size_limit_bytes: 1000000
  memory_max_entries: 100

circuit_breaker:
  failure_threshold: 3
  reset_timeout: 30.0
  half_open_max_calls: 1
"""

    yaml_path = systems_dir / "example.yaml"
    yaml_path.write_text(yaml_content, encoding="utf-8")
    return yaml_path
