# config/default.yaml

project:
  name: "autoevoextractor"
  log_level: "INFO"

llm:
  student:
    use_ollama: true
    model: "mistral-small3.1-24b-128k:latest"
    timeout: 600
    max_retries: 5
    temperature: 0.0
    rate_limit_delay: 10.0
    top_p: 0.1
    repeat_penalty: 1.2
    repeat_last_n: 2048
    ollama:
      ollama_base_url: "https://aicltr.itmo.ru/ollama"
      num_ctx: 128000
      num_predict: 4096
      repeat_penalty: 1.2
      stream: true
    non_ollama:
      max_tokens: 4096

  teacher:
    use_ollama: true
    model: "gpt-oss:120b"
    timeout: 1200
    max_retries: 2
    temperature: 0.5
    rate_limit_delay: 10.0
    top_p: 0.9
    repeat_penalty: 1.1
    repeat_last_n: 512
    ollama:
      ollama_base_url: "https://aicltr.itmo.ru/ollama"
      num_ctx: 100000
      num_predict: 8192
      repeat_penalty: 1.1
      stream: true
    non_ollama:
      max_tokens: 8192

parsing:
  parser: "docling" # docling, marker
  overwrite: false
  docling:
    device: "cpu" # cpu, cuda, mps
    num_threads: 4
    do_ocr: true
    do_table_structure: true
  marker:
    device: "cpu" # cpu, cuda

paths:
  pdf_dir: "data/pdf"
  parsed_dir: "data/parsed"
  ground_truth_dir: "data/ground_truth"
  splits_file: "data/splits.json"
  agents_dir: "data/agents"
  predictions_dir: "data/predictions"
  logs_dir: "logs"

optimization:
  total_load: 20
  train_split: 20
  num_candidates: 10
  num_trials: 70
  max_bootstrapped_demos: 1
  max_labeled_demos: 2
  minibatch: false
  minibatch_size: 1
  view_data_batch_size: 3
  metric_threshold: 1.0
  init_temperature: 0.5
  random_seed: 42
  use_cache: true
  verbose: true

task:
  name: "nanozymes"
  evaluation:
    float_tolerance: 0.05
    compare_fields:
      - "formula"
      - "activity"
      - "reaction_type"
      - "ph"
      - "temperature"
      - "surface"
      - "syngony"
      - "length"
      - "width"
      - "depth"
      - "km_value"
      - "vmax_value"
      - "c_min"
      - "c_max"
      - "c_const"
      - "ccat_value"
      - "km_unit"
      - "vmax_unit"
      - "c_const_unit"
      - "ccat_unit"